### ISSUE TITLE
CaDiCaL is no longer optional: misleading error message from configure.sh, plus auto download doesn't work on M1

### ISSUE THREAD

**Issue by polgreen** [cvc5/cvc5#6822]
**Describe the bug**
CaDiCaL used to be optional. Now it's not. I'm at commit d288f52dd82fe6590950758289e86ebcb039350d 

2 issues:

### Misleading error message
When i run configure.sh, it says 
~~~
CMake Error at cmake/deps-helper.cmake:54 (message):
  Could not find the optional dependency CaDiCaL in the system.  You can
  disable this dependency with --no-cadical, install it yourself or use
  --auto-download to let us download and build it for you.
~~~

This isn't right, I can't disable the dependency. 

### auto-download for CaDiCaL doesn't work on Mac M1. 

When I run  `./configure --auto-download` it successfully completes (will copy output to comment on issue), but running make gives the following error (I do have xcode command line tools installed):
~~~
 elipol@Elizabeths-MBP build % make
Scanning dependencies of target CaDiCaL-EP
[  0%] Creating directories for 'CaDiCaL-EP'
[  0%] Performing download step (download, verify and extract) for 'CaDiCaL-EP'
-- CaDiCaL-EP download command succeeded.  See also /Users/elipol/cvc5/build/deps/src/CaDiCaL-EP-stamp/CaDiCaL-EP-download-*.log
[  0%] No update step for 'CaDiCaL-EP'
[  1%] No patch step for 'CaDiCaL-EP'
[  1%] Performing configure step for 'CaDiCaL-EP'
-- CaDiCaL-EP configure command succeeded.  See also /Users/elipol/cvc5/build/deps/src/CaDiCaL-EP-stamp/CaDiCaL-EP-configure-*.log
[  1%] Performing build step for 'CaDiCaL-EP'
CMake Error at /Users/elipol/cvc5/build/deps/src/CaDiCaL-EP-stamp/CaDiCaL-EP-build-Production.cmake:37 (message):
  Command failed: 2

   '/Library/Developer/CommandLineTools/usr/bin/make' '-C' '/Users/elipol/cvc5/build/deps/src/CaDiCaL-EP/build' 'libcadical.a'

  See also

    /Users/elipol/cvc5/build/deps/src/CaDiCaL-EP-stamp/CaDiCaL-EP-build.log


-- Log output is:
In file included from ../src/analyze.cpp:1:
In file included from ../src/internal.hpp:8:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cassert:20:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
make[3]: *** [analyze.o] Error 1

CMake Error at /Users/elipol/cvc5/build/deps/src/CaDiCaL-EP-stamp/CaDiCaL-EP-build-Production.cmake:47 (message):
  Stopping after outputting logs.


make[2]: *** [deps/src/CaDiCaL-EP-stamp/CaDiCaL-EP-build] Error 1
make[1]: *** [CMakeFiles/CaDiCaL-EP.dir/all] Error 2
make: *** [all] Error 2
~~~

**Comment by polgreen** [comment]
output of configure.sh --auto-download
~~~

-- The C compiler identification is AppleClang 12.0.5.12050022
-- The CXX compiler identification is AppleClang 12.0.5.12050022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building Production build
-- Performing Test HAVE_FLAG_O3
-- Performing Test HAVE_FLAG_O3 - Success
-- Configuring with C flag '-O3'
-- Configuring with CXX flag '-O3'
-- Performing Test HAVE_FLAG_Wall
-- Performing Test HAVE_FLAG_Wall - Success
-- Configuring with C flag '-Wall'
-- Configuring with CXX flag '-Wall'
-- Performing Test HAVE_FLAG_Wno_unused_private_field
-- Performing Test HAVE_FLAG_Wno_unused_private_field - Success
-- Configuring with C flag '-Wno-unused-private-field'
-- Configuring with CXX flag '-Wno-unused-private-field'
-- Performing Test HAVE_FLAG_fexceptions
-- Performing Test HAVE_FLAG_fexceptions - Success
-- Configuring with C flag '-fexceptions'
-- Performing Test HAVE_FLAG_Wsuggest_override
-- Performing Test HAVE_FLAG_Wsuggest_override - Success
-- Configuring with CXX flag '-Wsuggest-override'
-- Performing Test HAVE_FLAG_Wnon_virtual_dtor
-- Performing Test HAVE_FLAG_Wnon_virtual_dtor - Success
-- Configuring with CXX flag '-Wnon-virtual-dtor'
-- Performing Test HAVE_FLAG_Wimplicit_fallthrough
-- Performing Test HAVE_FLAG_Wimplicit_fallthrough - Success
-- Configuring with C flag '-Wimplicit-fallthrough'
-- Configuring with CXX flag '-Wimplicit-fallthrough'
-- Performing Test HAVE_FLAG_Wshadow
-- Performing Test HAVE_FLAG_Wshadow - Success
-- Configuring with C flag '-Wshadow'
-- Configuring with CXX flag '-Wshadow'
-- Performing Test HAVE_FLAG_Wno_class_memaccess
-- Performing Test HAVE_FLAG_Wno_class_memaccess - Failed
-- Disabling unit tests since assertions are disabled.
-- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.9.1", minimum required is "3")
-- Found GMP 6.2.1: /usr/local/lib/libgmp.dylib
-- Looking for getc_unlocked
-- Looking for getc_unlocked - not found
-- Building CaDiCaL rel-1.4.1: /Users/elipol/cvc5/build/deps/lib/libcadical.a
-- Building Poly f543721215ec17a724dc86820a0430233931a637: /Users/elipol/cvc5/build/deps/lib/libpicpoly.a
-- Building SymFPU: /Users/elipol/cvc5/build/deps/include/
-- Performing Test CVC5_NEED_INT64_T_OVERLOADS
-- Performing Test CVC5_NEED_INT64_T_OVERLOADS - Success
-- Performing Test CVC5_NEED_HASH_UINT64_T_OVERLOAD
-- Performing Test CVC5_NEED_HASH_UINT64_T_OVERLOAD - Failed
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for C++ include ext/stdio_filebuf.h
-- Looking for C++ include ext/stdio_filebuf.h - not found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for ffs
-- Looking for ffs - found
-- Looking for optreset
-- Looking for optreset - found
-- Looking for sigaltstack
-- Looking for sigaltstack - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Looking for setitimer
-- Looking for setitimer - found
-- Performing Test STRERROR_R_CHAR_P
-- Performing Test STRERROR_R_CHAR_P - Failed
-- Found Git: /usr/bin/git (found version "2.30.1 (Apple Git-130)")
-- Found Java: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java (found version "1.8.0.282") found components: Runtime
-- Building ANTLR3 runtime: /Users/elipol/cvc5/build/deps/lib/libantlr3c.a
-- Downloading ANTLR3 JAR: /Users/elipol/cvc5/build/deps/share/java/antlr-3.4-complete.jar
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success

cvc5 1.0-prerelease

Build profile             : production

GPL                       : off
Best configuration        : off

Assertions                : off
Debug symbols             : off
Debug context mem mgr     : off

Dumping                   : on
Muzzle                    : off
Statistics                : on
Tracing                   : off

ASan                      : off
UBSan                     : off
TSan                      : off
Coverage (gcov)           : off
Profiling (gprof)         : off
Unit tests                : off
Valgrind                  : off

Shared libs               : on
Static binary             : off
Python bindings           : off
Java bindings             : off
Python2                   : off

ABC                       : off
CryptoMiniSat             : off
GLPK                      : off
Kissat                    : off
LibPoly                   : on
CoCoALib                  : off

Build libcvc5 only        : off
MP library                : gmp
Editline                  : off

Api docs                  : off


CPPLAGS (-D...): NDEBUG CVC5_DUMPING CVC5_STATISTICS_ON CVC5_USE_POLY
CXXFLAGS       : -O3 -Wall -Wno-unused-private-field -Wsuggest-override -Wnon-virtual-dtor -Wimplicit-fallthrough -Wshadow
CFLAGS         : -O3 -Wall -Wno-unused-private-field -fexceptions -Wimplicit-fallthrough -Wshadow
Linker flags   :

Install prefix : /usr/local

cvc5 license: modified BSD

Note that this configuration is NOT built against any GPL'ed libraries, so
it is covered by the (modified) BSD license.  This is, however, not the best
performing configuration of cvc5.  To build against GPL'ed libraries which
improve cvc5's performance, re-configure with '-DENABLE_GPL -DENABLE_BEST'.

Now change to 'build' and type 'make', followed by 'make check' or 'make install'.

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/elipol/cvc5/build
~~~

**Comment by nafur** [comment]
Thanks for the issue. I'll fix the error message soon.

I'm somewhat puzzled about the include issue with `cassert`, but it seems to me that there is something weird about your xcode installation: solutions for, e.g., https://github.com/xamarin/urho/issues/363, https://www.rosettacommons.org/node/9436, https://root-forum.cern.ch/t/fatal-error-assert-h-file-not-found/18805, https://apple.stackexchange.com/questions/373316/missing-headers-in-macos-10-15-catalina all seem to boil down to fixing the xcode installation. The last one also mentions that the include lives at some new place. Can you check whether this is the case for you?

**Comment by polgreen** [comment]
The headers are exactly where the last link you gave says they are, but that doesn't really help me. All of the solutions in the links seem to be one of:
1 - xcode-select --install 
2 - sudo xcodebuild -license
3 - reinstall xcode from scratch
all of which I've tried. 

I don't think there's anything particularly weird about my XCode installation, it's a fresh installation via the app store (i uninstalled and reinstalled trying to fix this issue), and I can compile C files with assert.h in them fine using gcc/clang

I can build CaDiCaL from source, is there a way to point the config file to the CaDiCaL I have already built?

**Comment by mpreiner** [comment]
You can use `./configure.sh --dep-path=<path-to-cadical-install>` to point the build system to dependencies already installed on your system (and which are not installed to standard locations).

**Comment by polgreen** [comment]
It's expecting something built for x86, and not arm. 

Is this something I can configure somewhere, can I build CVC4 for arm64? Or does CVC4 need to build for x86_64, and so I need to build CaDiCal for x86?

**Comment by mpreiner** [comment]
> It's expecting something built for x86, and not arm.

I'm not sure I understand. Can you elaborate?

You are trying to build cvc5 and CaDiCaL on an Apple M1, right? Compiling cvc5 natively on arm64 should work out-of-the-box without any specific configure options.

**Comment by polgreen** [comment]
> You are trying to build cvc5 and CaDiCaL on an Apple M1, right?
Yes

> Compiling cvc5 natively on arm64 should work out-of-the-box without any specific configure options.
- when I let it compile CaDiCaL by itself, it gives error messages about assert.h not existing
- when I compile CaDiCaL first, and then compile CVC4, it gives an error message about linking that says something like: compiling for x86_64 and cadical binary is built for arm64. 

Let me try to reproduce

**Comment by polgreen** [comment]
I appear to be able to make this work if I build CaDiCaL for x86_64

**Comment by 4tXJ7f** [comment]
On macOS, CaDiCaL can also be installed via homebrew (`brew install cadical`). I've recently added it to the core repository. However, that would probably not solve the problem that you are seeing where it seems to try to compile cvc5 for x86 instead of ARM64. I'll take a look. Compiling it for x86 and then running it with Rosetta 2 is probably not ideal in terms of performance, so it would be good to figure this out.

**Comment by 4tXJ7f** [comment]
Small update: The `cassert` issue should be fixed in #6828.

**Comment by polgreen** [comment]
Ok, thanks, that works perfectly for x86_64.

I still can't build for arm64. I have 2 cmakes: an arm64e one and an x86_64 one (iirc I installed the x86_64 one because I couldn't get cvc4 to build with the native arm one). 'make' is a universal binary with 2 architectures.
- If I use the x86_64 cmake, with your new PR, everything works perfectly, but I get an x86_64 binary. 
- If I use the arm64e cmake, I get the following error:

~~~
[ 10%] Built target gen-expr
CMake Error at /Users/elipol/cvc5/build/deps/src/ANTLR3-EP-runtime-stamp/ANTLR3-EP-runtime-configure-Production.cmake:37 (message):
  Command failed: 1

   '/opt/homebrew/Cellar/cmake/3.20.5/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/Users/elipol/cvc5/build/deps/src/ANTLR3-EP-runtime-stamp/ANTLR3-EP-runtime-configure-Production-impl.cmake'

  See also

    /Users/elipol/cvc5/build/deps/src/ANTLR3-EP-runtime-stamp/ANTLR3-EP-runtime-configure.log


-- Log output is:
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for xlc... no
checking for aCC... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... Invalid configuration `aarch64-apple-darwin20.3.0': machine `aarch64-apple' not recognized
configure: error: /bin/sh /Users/elipol/cvc5/build/deps/src/ANTLR3-EP-runtime/config.sub aarch64-apple-darwin20.3.0 failed
CMake Error at /Users/elipol/cvc5/build/deps/src/ANTLR3-EP-runtime-stamp/ANTLR3-EP-runtime-configure-Production-impl.cmake:39 (message):
  Command failed (1):

   '/Users/elipol/cvc5/build/deps/src/ANTLR3-EP-runtime/configure' '--with-pic' '--disable-antlrdebug' '--prefix=/Users/elipol/cvc5/build/deps' '--srcdir=/Users/elipol/cvc5/build/deps/src/ANTLR3-EP-runtime' '--disable-shared' '--enable-static' '--enable-64bit' '--host='



CMake Error at /Users/elipol/cvc5/build/deps/src/ANTLR3-EP-runtime-stamp/ANTLR3-EP-runtime-configure-Production.cmake:47 (message):
  Stopping after outputting logs.


make[2]: *** [deps/src/ANTLR3-EP-runtime-stamp/ANTLR3-EP-runtime-configure] Error 1
~~~

**Comment by 4tXJ7f** [comment]
@polgreen With commit b2c4184f1148ba1c51011ee6dd8341b9f204f54e, cvc5 should now compile on an M1 Mac natively (at least it did for me). Could you please give it a try and see if it works for you, too? There are two additional issues that I've found while testing cvc5 on an M1 Mac (fixed in #6856 and #6857) but those shouldn't affect usability too much.

**Comment by polgreen** [comment]
Argh sorry, thought I'd responded to this. 

It works! I get an arm binary when I use the arm cmake

I do get a bunch of warnings like this though (with either arm or x86 cmake)
~~~
warning(200): /Users/elipol/cvc5/src/parser/cvc/Cvc.g:1832:5: 
Decision can match input such as "LPAREN STRING_REV_TOK LPAREN" using multiple alternatives: 3, 5

As a result, alternative(s) 5 were disabled for that input
~~~

**Comment by 4tXJ7f** [comment]
No problem, thank you for confirming. Yes, those warnings are (unfortunately) expected. They are emitted by ANTLR (the parser generator that we use), which we are planning to replace. Additionally, the majority of the warnings are in the CVC parser, which will be removed before the release. Since the compilation on M1 seems to work and the warnings are unrelated to that, I am closing the issue. Feel free to reopen or open an new issue if you encounter any other issues.
